# O token tem validade de 1 dia, logo, se o token expirar, é necessário gerar um novo token

### Request 1 -> Receber os alunos do responsável Bob Doe (2 filhos)
GET http://localhost:3000/responsible/student HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjEsImVtYWlsIjoiYm9iZG9lQG1haWwuY29tIiwiaWF0IjoxNjkxMTU5NzA2LCJleHAiOjE2OTEyNDYxMDZ9.hoCPIXghjgUoxCSPehA5yJ5pAV6hQuHlJVnLRCURx4M

### Request 2 -> Receber os alunos da responsável Molly Doe (1 filho)
GET http://localhost:3000/responsible/student HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjIsImVtYWlsIjoibW9sbHlkb2VAbWFpbC5jb20iLCJpYXQiOjE2OTExNzE5MzksImV4cCI6MTY5MTI1ODMzOX0.KzWUh5ns_8kX--W_ydEoQFGIrH7y9tCM0iyZu70Gyig

### Request 3 -> Jwt expirado
GET http://localhost:3000/responsible/student HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjEsImVtYWlsIjoiYm9iZG9lQG1haWwuY29tIiwiaWF0IjoxNjkxMDAxMDI2LCJleHAiOjE2OTEwODc0MjZ9.cNYdqZhStTyp7HvRYzYOFuoUVj7jCdg5A4qtx2ZCnug

### Request 4 -> Jwt inválido (invalid signature)
GET http://localhost:3000/responsible/student HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjEsImVtYWlsIjoiYm9iZG9lQG1haWwuY29tIiwiaWF0IjoxNjkxMDAxMDI2LCJleHAiOjE2OTEwODc0MjZ9.cNYdqZhStTyp7HvRYzYOFuoUVj7jCdg5A4qtx2ZCnu