# O token tem validade de 1 dia, logo, se o token expirar, é necessário gerar um novo token

### Request 1 -> Receber 2 logs de John (id 1) (Bob)
GET http://localhost:3000/responsible/student/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjEsImVtYWlsIjoiYm9iZG9lQG1haWwuY29tIiwiaWF0IjoxNjkxMTU5NzA2LCJleHAiOjE2OTEyNDYxMDZ9.hoCPIXghjgUoxCSPehA5yJ5pAV6hQuHlJVnLRCURx4M

### Request 2 -> Receber 1 log de Ana (id 2) (Bob)
GET http://localhost:3000/responsible/student/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjEsImVtYWlsIjoiYm9iZG9lQG1haWwuY29tIiwiaWF0IjoxNjkxMTU5NzA2LCJleHAiOjE2OTEyNDYxMDZ9.hoCPIXghjgUoxCSPehA5yJ5pAV6hQuHlJVnLRCURx4M

### Request 3 -> Não receber logs do filho de Molly (pois não foram criados)
GET http://localhost:3000/responsible/student/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoicmVzcG9uc2libGUiLCJzdWIiOjIsImVtYWlsIjoibW9sbHlkb2VAbWFpbC5jb20iLCJpYXQiOjE2OTExNzE5MzksImV4cCI6MTY5MTI1ODMzOX0.KzWUh5ns_8kX--W_ydEoQFGIrH7y9tCM0iyZu70Gyig